--- #YAML:1.0
name:               Class-Declarative
version:            0.02
abstract:           Provides a declarative framework for Perl
author:
    - Michael Roberts <michael@vivtek.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Parse::Indented:      0
    Parse::RecDescent::Simple:  0
    Test::More:           0
    XML::xmlapi:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
